---
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
        types: [ python ]
      - id: trailing-whitespace
        types: [ python ]
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
  #  - repo: https://github.com/gruntwork-io/pre-commit
  #    rev: v0.1.12
  #    hooks:
  #      - id: shellcheck
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/hakancelik96/unimport
    rev: 0.8.3
    hooks:
      - id: unimport
        args: [ --remove, --requirements, --include-star-import ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      # https://github.com/pre-commit/mirrors-mypy/issues/3
      # https://github.com/pre-commit/pre-commit/issues/1351
      additional_dependencies:
        - types-aiofiles
        - types-click
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'
    hooks:
      - id: bandit
        files: .py$
        args: [
            --configfile, "bandit.yaml",
            # TODO: work on this files !
            --exclude, "src/pydbsrt/tools/ffmpeg_wrapper,src/pydbsrt/tools/ffmpeg_tools/",
        ]
